python3 main_3grams_1to5_ordered_inbound.py
python3 main_3grams_1to5_random_inbound.py
python3 main_3grams_1to5_ordered_outbound.py
python3 main_3grams_1to5_random_outbound.py

python3 main_2grams_1to5_ordered_inbound.py
python3 main_2grams_1to5_random_inbound.py
python3 main_2grams_1to5_ordered_outbound.py
python3 main_2grams_1to5_random_outbound.py
